### ISSUE TITLE
Add preview processing capability and crop preview

### ISSUE THREAD

**Issue by deividasstr** [onseok/peekaboo#77]
Hey, 

I am working on a KMP compose app where I need a barcode scanner.

For camera preview, I could use this lib. But I need to be able to:
* process each frame 
* be able to have a [barcode frame](https://m2.material.io/design/machine-learning/barcode-scanning.html#components) for processing (still not sure if this cropping has to be processed before outputting a `ByteArray`, or it can be calculated after)

I guess a simpler way would be to expose another callback `onFrame`, similar to `onCapture`. Just not sure about a performance. Or some sort of stream of ByteArray (coroutines Flow '<ByteArray'> ?).

2 questions:
* would you accept such contribution?
* any suggestions/pointers on the topic?

Thanks in advance 🙇

**Comment by l2hyunwoo** [comment]
Hello @deividasstr thanks for good suggestion! 👍🏻 

I think it should be needed @onseok's opinion, but I'll answer in terms of mine. Also since I'm Android developer, I can't give you advices of implementation in iOS env.

In this case, Rect(struct that represents area you want to crop) parameter should be passed and onFrame(type that I think is `(ImageIntermediateResult(wrapping ImageProxy of camerax)) -> Unit` is proper) also should be passed i think.

But this way is too android-istic way so I want to suggest get feedbacks to you or @onseok.

Thanks for suggest good feature one more time 😄
